# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: 
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Salamandre85"

# Avatar image path
avatar: "./images/Banner.png"

# Name section text
name: "@salamandre85"

# Tagline section text
tagline: |-
    Saul Sambono: Multidisciplinary artist in Canberra, Australia â€” appearing as     
      (The)Salamandre85,     
      Strongman Sadman,     
      and frank_Blitz

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-bluesky"
      text: "My BlueSky has all of the things"
      url: "https://bsky.app/profile/salamandre85.bsky.social"
      title: "Salamandre85's BlueSky"
      alt: "Salamandre85's BlueSky"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Salamandre85's visual work"
      url: "https://www.instagram.com/Salamandre85/"
      title: "Instagram"
      alt: "Salamandre85's Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Performer Profile on Instagram"
      url: "https://www.instagram.com/strongman.sadman/"
      title: "Instagram"
      alt: "Strongman Sadman's Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "Salamandre85 streaming games and tech on YouTube"
      url: "https://www.youtube.com/@thesalamandre85"
      alt: "The Salamandre85 on YouTube"
      title: "The Salamandre85 on YouTube"
      target: "_blank"
  - link:
      icon: "fa-solid fa-rss"
      text: "Personal Portfolio"
      url: "https://saulsambono.info/"
      alt: "Saul's Website"
      title: "Saul's Website"
      target: "_blank"
  

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/salamandre85.bsky.social"
      title: "Salamandre85's BlueSky"
      alt: "Salamandre85's BlueSky"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/salamandre85"
      title: "Salamandre85's Twitter"
      alt: "Salamandre85's Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/Salamandre85/"
      title: "Instagram"
      alt: "Salamandre85's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/strongman.sadman/"
      title: "Instagram"
      alt: "Strongman Sadman's Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:contact@saulsambono.info"
      title: "Email: contact@saulsambono.info"
      alt: "contact@saulsambono.info"
      target: "_blank"

# Footer text
footer: |
    Hi ðŸ‘‹ I'm Saul Sambono. I'm a creator living in the Australian Capital Territory 
    I make works and perform under the names Salamandre85, Strongman Sadman, and frank_Blitz
    My social network is currently under renovation, but the best places to follow me are Instagram and BlueSky

# Footer copyright message
# Linkyee is a 100% free, open-source projectâ€”feel free to modify the copyright message as you like. :)
copyright: >
  Â© 2025  <a href="https://saulsambono.info" target="_blank">Saul Sambono</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
